1. Getting the data

2. Importing Libararies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

3. Importing a Dataset

In [61]:
df = pd.read_csv("Data.csv")

Extracting Dependent and Independent Variables

In [18]:
x = df.iloc[:,:-1] #gives independent variables
y = df.iloc[:,3] #gives dependent variable

4. Handling missing data

In [3]:
from sklearn.impute import SimpleImputer

In [62]:
# x.iloc[:,1:]
imputer = SimpleImputer(strategy = 'mean')
out = imputer.fit_transform(df[["Age", "Salary"]])

In [63]:
df['Age'] = out[:,0]
df['Salary'] = out[:,1]

In [64]:
df.to_csv("Data2.csv", index = False)

5. Encoding Categorical data

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
lblenc = LabelEncoder()
df['Purchased'] = lblenc.fit_transform(df['Purchased'])

In [21]:
df

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1

One Hot Encoder

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
onehotenc = OneHotEncoder()
enc_country = onehotenc.fit_transform(df[['Country']]).toarray()
enc_country1 = onehotenc.fit_transform(df[['Country']])

In [29]:
df.head(3)

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0

In [32]:
enc_country

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [31]:
#getting a dummy variable
pd.get_dummies(df['Country'])

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [33]:
enc_country2 = lblenc.fit_transform(df[['Country']])

c:\Users\hiten\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [34]:
enc_country2

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

Binning

In [36]:
sal_name = ['Low', 'Medium', 'High']
bins = np.linspace(df.Salary.min(), df.Salary.max(), 4)

In [39]:
df['Salary Group'] = pd.cut(df.Salary,bins, labels = sal_name, include_lowest = True)

In [41]:
bins

array([48000.        , 59666.66666667, 71333.33333333, 83000.        ])

In [44]:
df1 = df.iloc[7:10]

In [46]:
df2 = pd.concat([df, df1])

In [47]:
df2

Country        Age        Salary  Purchased Salary Group
0   France  44.000000  72000.000000          0         High
1    Spain  27.000000  48000.000000          1          Low
2  Germany  30.000000  54000.000000          0          Low
3    Spain  38.000000  61000.000000          0       Medium
4  Germany  40.000000  63777.777778          1       Medium
5   France  35.000000  58000.000000          1          Low
6    Spain  38.777778  52000.000000          0          Low
7   France  48.000000  79000.000000          1         High
8  Germany  50.000000  83000.000000          0         High
9   France  37.000000  67000.000000          1       Medium
7   France  48.000000  79000.000000          1         High
8  Germany  50.000000  83000.000000          0         High
9   France  37.000000  67000.000000          1       Medium

In [49]:
tarining_datatset = df2.iloc[0:10]
print(tarining_datatset)
testing_dataset = df2.iloc[10:13]
print(testing_dataset)

   Country        Age        Salary  Purchased Salary Group
0   France  44.000000  72000.000000          0         High
1    Spain  27.000000  48000.000000          1          Low
2  Germany  30.000000  54000.000000          0          Low
3    Spain  38.000000  61000.000000          0       Medium
4  Germany  40.000000  63777.777778          1       Medium
5   France  35.000000  58000.000000          1          Low
6    Spain  38.777778  52000.000000          0          Low
7   France  48.000000  79000.000000          1         High
8  Germany  50.000000  83000.000000          0         High
9   France  37.000000  67000.000000          1       Medium
   Country   Age   Salary  Purchased Salary Group
7   France  48.0  79000.0          1         High
8  Germany  50.0  83000.0          0         High
9   France  37.0  67000.0          1       Medium


6. Splitting the dataset into training and testing

In [50]:
from sklearn.model_selection import train_test_split

In [65]:
df = pd.read_csv("Data2.csv")

In [67]:
x = df.iloc[:,:-1] #gives independent variables
y = df.iloc[:,3] #gives dependent variable

In [116]:
trainx, testx, trainy, testy = train_test_split(x, y, test_size = 0.2, random_state = 0) 
#random state menas that no random sleection of data is going to be there
#i.e., you will have all the values inside train and test data same everytime you execute this
testx

Country   Age   Salary
2  Germany  30.0  54000.0
8  Germany  50.0  83000.0

In [117]:
print(f"Number of rows in training dataset = {trainx.shape[0]}")
print(f"Number of rows in testing dataset = {testx.shape[0]}")

Number of rows in training dataset = 8
Number of rows in testing dataset = 2


In [118]:
df2

Country        Age        Salary  Purchased Salary Group
0   France  44.000000  72000.000000          0         High
1    Spain  27.000000  48000.000000          1          Low
2  Germany  30.000000  54000.000000          0          Low
3    Spain  38.000000  61000.000000          0       Medium
4  Germany  40.000000  63777.777778          1       Medium
5   France  35.000000  58000.000000          1          Low
6    Spain  38.777778  52000.000000          0          Low
7   France  48.000000  79000.000000          1         High
8  Germany  50.000000  83000.000000          0         High
9   France  37.000000  67000.000000          1       Medium
7   France  48.000000  79000.000000          1         High
8  Germany  50.000000  83000.000000          0         High
9   France  37.000000  67000.000000          1       Medium

7. Feature Scaling

1. Standardization => New Value = [original value - (mean original value)]/Standard Deviation
2. Normalization => New Value = [Original Value - min(original value)]/[max(original value) - min(originla value)]

In [119]:
from sklearn.preprocessing import StandardScaler

In [129]:
x1 = df2[['Age', 'Salary']]
y1 = df2['Purchased']
x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size = 0.2, random_state = 0)

In [130]:
std_x = StandardScaler()
#print(f"Training data before Feature scaling:\n {x_train.head(5)}")
x_train = std_x.fit_transform(x_train)
print(f"\nTraining data after Feature scaling:\n {x_train}")



Training data after Feature scaling:
 [[ 1.15293518  1.10653329]
 [-1.26018496 -1.16095296]
 [ 1.42105964  1.46933109]
 [-1.66237165 -1.70514966]
 [ 1.15293518  1.10653329]
 [-0.32174935  0.01813989]
 [-0.18768712 -0.52605681]
 [ 0.61668626  0.47163714]
 [-0.58987381 -0.79815516]
 [-0.32174935  0.01813989]]


In [131]:
x_test = std_x.transform(x_test)

In [132]:
x_test

array([[-0.0834165 , -1.34235186],
       [ 1.42105964,  1.46933109],
       [ 0.08043734, -0.27411389]])